/*
 * @route    /
 * @desc     Home page with info, how it works, discover, featured creators, "become a creator", etc
 * @access   Public
 * @wallet   Not required
 */

import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
// @ts-ignore
import styles from '../styles/Home.module.css';
// import { usePublication } from '../hooks/useCreator';
import useCreatorSignup from '../hooks/useCreatorSignup';
import { ConnectWallet } from '../components/ConnectWallet';
import { Navbar } from '../components/Navbar';
import { DashLink } from '../components/DashLink';

const IndexPage = () => {
  const hi = useCreatorSignup();
  console.log(hi);

  // useEffect(() => {
  //   setUsername('jacob');
  //   setPublicationName('my newsletter');
  //   setPublicationDescription('reeeaalllyyyyy cool newsletter');
  // }, []);

  return (
    <div className={styles.container}>
      {/* @ts-ignore */}
      <Head>
        <title>News NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <main className={styles.main}>
        <div className={styles.contentcontainer}>
          <span>
            <img
              className={styles.svgLogo}
              src="newsnft_logo.svg"
              alt="newsnft logo"
            />
          </span>

          {/* <input type="file" onChange={e => setProfileImg(e.target.files[0])} />
          <input
            type="file"
            onChange={e => setPublicationImg(e.target.files[0])}
          />
          <div>
            <button onClick={() => signup()}>
              {isLoading ? 'loading...' : 'sign up...'}
            </button>
          </div> */}

          <h1 className={styles.title}>
            Your News, Minted
            <br></br>NEWS NFT.
          </h1>

          <ConnectWallet />

          <div className={'text-center'}>
            <div className={styles.grid}>
              <div className={styles.card}>
                <h2 className={'font-bold'}>Let's Get Started 🚀</h2>
                <p className={'text-sm'}>
                NewsNFT is a platform for experienced web3 enthusiasts and the NFT-curious alike. 😁 Combining the awesome features of both NFTs and newsletters, creators can mint their newsletters on the blockchain and airdrop them to their subscribers!
                </p>
                <br />
<DashLink/>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default IndexPage;
